### PR TITLE
Add out of memory as disconnect reason

### PR DESCRIPTION
**Pull request by lgrahl**

### CODE REVIEW

**Comment by dbrgn** [comment]
Looks good, but how do you send this if the app is killed by the OOM killer? In the [`onTrimMemory`](https://developer.android.com/reference/android/app/Application.html#onLowMemory()) callback? Unfortunately it probably depends on the device with which level and how quickly `onTrimMemory` is called by the OS. It's possible that on some devices the app will be killed at a certain low level, while on other devices the app will continue to run fine (in which case we shouldn't prematurely close the connection).

**Comment by lgrahl** [comment]
You can catch `OutOfMemoryError`.

**Comment by dbrgn** [comment]
> You can catch `OutOfMemoryError`.

Ah, that's probably a different story from the OOM killer. It only happens when allocating big chunks of memory, I think. 

When an `OutOfMemoryError` happens, can code still be executed or will the entire process be killed? If we can still run code and send network packets, then yes, this disconnect reason makes sense!

**Comment by lgrahl** [comment]
> When an `OutOfMemoryError` happens, can code still be executed or will the entire process be killed?

That exception is basically the equivalent of `malloc` failing.

> If we can still run code and send network packets, then yes, this disconnect reason makes sense!

Yep!

**Pull request merged**
